#server:
#  port: 8080
#
#spring:
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: "jdbc:mysql://localhost:3306/androriaDB?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
#    username: root
#    password: 
#
#  servlet:
#    multipart:
#      max-file-size: 50MB
#      max-request-size: 50MB
#
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true
#
#  #  sql:
#  #    init:
#  #      mode: always
#
#  jpa:
#    # Choose either MySQL 8 or MySQL 5 below
#    # For MySQL 8
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    #For MySQL 5
#    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: update
#    open-in-view: false
#    properties:
#      hibernate:
#        format_sql: true
#  #    defer-datasource-initialization: true

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL:}
    username: ${JDBC_DATABASE_USERNAME:}
    password: ${JDBC_DATABASE_PASSWORD:}
  sql:
    init:
      mode: always
  jpa:
    # Choose either MySQL 8 or MySQL 5 below
    # For MySQL 8
    #database-platform: org.hibernate.dialect.MySQL8Dialect
    #For MySQL 5
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #For ProstreSQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server.port: ${PORT:8080}

#Cloudinary Properties
#cloudinary:
#  api-key: 988518893397762
#  api-secret: 
#  cloud-name: malmsuite

#schedulers:
#  cronReviews: "*/50 * * * * *"
#  cronReviewsTemp: "30 7 18 9 * *"
#  cronDeleteBrowsingUsers: "30 7 18 9 * *"
#  cronAddVipGuest: "*/100 * * * * *"

#androria:
#  andraop.enabled: true
#  andrmodifying.enabled: true




#server:
#  port: 8000
#
#spring:
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: "jdbc:mysql://localhost:3306/hydrocalcDB?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
#    username: root
#    password: 
#
#  servlet:
#    multipart:
#      max-file-size: 50MB
#      max-request-size: 50MB
#
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true
#
#  #  sql:
#  #    init:
#  #      mode: always
#
#  jpa:
#    # Choose either MySQL 8 or MySQL 5 below
#    # For MySQL 8
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    #For MySQL 5
#    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: update
#    open-in-view: false
#    properties:
#      hibernate:
#        format_sql: true
#  #    defer-datasource-initialization: true
#
#  #Cloudinary Properties
#cloudinary:
#  api-key: 988518893397762
#  api-secret: ${CLOUDINARY_API_SECRET}
#  cloud-name: malmsuite
#
#schedulers:
#  cronReviews: "*/50 * * * * *"
#  cronReviewsTemp: "30 7 18 9 * *"
#  cronDeleteBrowsingUsers: "30 7 18 9 * *"
#  cronAddVipGuest: "*/100 * * * * *"
#
#androria:
#  andraop.enabled: true
#  andrmodifying.enabled: true
